### ISSUE TITLE
Change a field text on https://www.topcoder.com/direct/contest/detail.action?projectId=  page

### ISSUE THREAD

**Issue by aah-74** [appirio-tech/direct-app#431]
The detail page of the Challenge shows text field for Estimated Efforts. 
The current field text is Effort Hours Estimate.  Change it to Effort Estimate
![screencapture-topcoder-direct-contest-detail-action](https://user-images.githubusercontent.com/40483249/41759300-5427e81c-760b-11e8-991e-f2bcc3dec0f9.jpg)

**Comment by aah-74** [comment]
The data in Tool Tip associated to the field also needs to change.

**Comment by aah-74** [comment]
Here is the text that the field should display  for both ( new challenge creation form and the overview page)

Effort Estimate ( in Person Days)


For Tool tip please use text below
onsite efforts in person days * 6 + offshore efforts in person days

**Comment by ajefts** [comment]
@skyhit fyi, for the specific label text.

**Comment by skyhit** [comment]
@ajefts that is implemented, we need to revert the changes for backend.

**Comment by ajefts** [comment]
This has been released.

**Comment by aah-74** [comment]
@ajefts Can you please check if any calculations are done while the requested label change?

**Comment by ajefts** [comment]
@aah-74 Yes, we are doing a calc.  Here is the scenario:

We're storing the value in the DB as hours (since we wanted that level of granularity in the platform regardless of what we choose to display in the front end).  So, Direct is now converting the # of days entered into # of hours.  When it reads the value to display it, it converts hours (from DB) to days.  The issue is that for data entered prior to the change, it's still doing the conversion since it doesn't know how to distinguish.  

I'm looking for some advice on how to best handle this.  We can do a data update, but I'm not sure of the best way to identify the challenges that should be updated.  Here is the list of all challenges with Effort set to a value:  https://topcoder.looker.com/looks/1031

Any thoughts on how we could do a bulk update?
